name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.7
  - numpy
  - pandas
  - ipyvolume
  - pillow
  - shapely
  - matplotlib    
  - pip:
    - nbgitpuller
    - geopy
    - geojson
    
