name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.7
  - numpy
  - pandas
  - ipyvolume
  - pillow
  - pip
  - shapely
  - matplotlib  
  - ipyleaflet
  - pip:
    - nbgitpuller
    - geopy
    - geojson
